apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rbitly-ingress
  namespace: rbitly
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: rbitly.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rbitly
                port:
                  number: 3000
